/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mumumusuc_stb_StbImageNative */

#ifndef _Included_com_mumumusuc_stb_StbImageNative
#define _Included_com_mumumusuc_stb_StbImageNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_stb_StbImageNative_nInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nInfoFromMemory
 * Signature: (Ljava/nio/Buffer;I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_stb_StbImageNative_nInfoFromMemory
  (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nInfoFromCallbacks
 * Signature: (Lcom/mumumusuc/stb/StbIOCallbacks;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_stb_StbImageNative_nInfoFromCallbacks
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nIs16BitFromMemory
 * Signature: (Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_stb_StbImageNative_nIs16BitFromMemory
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nIs16BitFromCallbacks
 * Signature: (Lcom/mumumusuc/stb/StbIOCallbacks;)I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_stb_StbImageNative_nIs16BitFromCallbacks
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nLoadFromMemory
 * Signature: (Ljava/nio/Buffer;I[I[I[II)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_mumumusuc_stb_StbImageNative_nLoadFromMemory
  (JNIEnv *, jclass, jobject, jint, jintArray, jintArray, jintArray, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nLoadFromCallback
 * Signature: (Lcom/mumumusuc/stb/StbIOCallbacks;[I[I[II)Ljava/nio/Buffer;
 */
JNIEXPORT jobject JNICALL Java_com_mumumusuc_stb_StbImageNative_nLoadFromCallback
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jintArray, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nSetUnpremultiplyOnLoad
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_stb_StbImageNative_nSetUnpremultiplyOnLoad
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nConvertIphonePngToRgb
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_stb_StbImageNative_nConvertIphonePngToRgb
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nSetFlipVerticallyOnLoad
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_stb_StbImageNative_nSetFlipVerticallyOnLoad
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mumumusuc_stb_StbImageNative
 * Method:    nFailureReason
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mumumusuc_stb_StbImageNative_nFailureReason
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
